global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Add your web server metrics endpoint here if implemented
  # - job_name: 'webserver'
  #   static_configs:
  #     - targets: ['webserver:9090']  # Assuming metrics on port 9090
  #   metrics_path: /metrics
  #   scrape_interval: 5s